TIMEOUT 10
DEFAULT arch
LABEL arch
    LINUX /boot/zImage
    INITRD /boot/initramfs-linux.img
    FDT /boot/dtbs/qcom-msm8226-samsung-matisse3g.dtb
    APPEND root=LABEL=alarm-matisse3g rw rootwait rootfstype=ext4 console=tty0 lk2nd.pass-simplefb=xrgb8888,autorefresh wcn36xx.disable_11b=1

# Variant: without initramfs (kernel mounts root directly)
# LABEL arch-direct
#     LINUX /boot/zImage
#     FDT /boot/dtbs/qcom-msm8226-samsung-matisse3g.dtb
#     APPEND root=LABEL=alarm-matisse3g rw rootwait rootfstype=ext2 console=tty0 lk2nd.pass-simplefb=xrgb8888,autorefresh wcn36xx.disable_11b=1
